### ISSUE TITLE
Add docker compose file

### ISSUE THREAD

**Issue by rlh1994** [snowplow-incubator/snowplow-micro#128]
**Is your feature request related to a problem? Please describe.**
Using the default provided `docker run` script you generate a new container every time you start and stop the image, using a compose file avoids this issue and allows for easier mangement of configurations to the container.

**Describe the solution you'd like**
A docker compose file added to the repo, I am not sure if it would be part of the repo proper or just in the readme.

**Describe alternatives you've considered**
Add `--rm` tag to call

**Additional context**
I believe the basic file would be as follows, but there may be further options that are defaults that could be added so it's easier to customise:

```yml
version: "1.0"
name: snowplow_micro

services:
  micro:
    image: snowplow/snowplow-micro:latest
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./example/
        target: /config
    command: --collector-config /config/micro.conf --iglu /config/iglu.json
```
